// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {devices} from '../models';

export function ChooseBackgroundImage():Promise<string>;

export function GetConfig():Promise<main.ConfigView>;

export function GetServiceStatus():Promise<main.ActionResult>;

export function GetStatus():Promise<main.AppStatus>;

export function GetTheme():Promise<main.ThemeView>;

export function InstallService(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean):Promise<main.ActionResult>;

export function ListDevices():Promise<Array<devices.Device>>;

export function ReloadLoopback(arg1:boolean):Promise<main.ActionResult>;

export function RestartService():Promise<main.ActionResult>;

export function SaveUserSettings(arg1:main.UserSettings):Promise<main.ActionResult>;

export function SetTheme(arg1:string):Promise<main.ActionResult>;

export function ShowLoopback():Promise<main.LoopbackView>;

export function StartService():Promise<main.ActionResult>;

export function StopService():Promise<main.ActionResult>;

export function WriteConfig(arg1:boolean,arg2:boolean):Promise<main.ActionResult>;

export function WriteLoopback(arg1:boolean,arg2:boolean):Promise<main.ActionResult>;
