// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseBackgroundImage() {
  return window['go']['main']['App']['ChooseBackgroundImage']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function InstallService(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallService'](arg1, arg2, arg3, arg4);
}

export function ListAudioSources() {
  return window['go']['main']['App']['ListAudioSources']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ReloadLoopback(arg1) {
  return window['go']['main']['App']['ReloadLoopback'](arg1);
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function SaveUserSettings(arg1) {
  return window['go']['main']['App']['SaveUserSettings'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowLoopback() {
  return window['go']['main']['App']['ShowLoopback']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function WriteConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteConfig'](arg1, arg2);
}

export function WriteLoopback(arg1, arg2) {
  return window['go']['main']['App']['WriteLoopback'](arg1, arg2);
}
